//! Ingredient-table parser for `cooking.lua` plus the ocean-fish generator in
//! `prefabs/oceanfishdef.lua`.
//!
//! `AddIngredientValues` is the authoritative list used by the crock pot's
//! `itemtestfn` (`cooking.IsCookingIngredient`). The game also creates
//! `_cooked` / `_dried` variants implicitly; some of those names are legacy or
//! virtual and do not correspond to real prefabs, so the selectable panel is
//! further filtered with the real-prefab allow-list parsed from
//! `scrapbook_prefabs.lua`.

use crate::error::{Error, Result};
use crate::models::CookingIngredient;
use crate::parser::string_literal_text;
use full_moon::ast::{self, Ast};
use std::collections::{BTreeMap, BTreeSet};

#[derive(Debug, Clone, PartialEq)]
pub struct IngredientValue {
    pub tags: BTreeMap<String, f64>,
}

impl IngredientValue {
    fn new() -> Self {
        Self {
            tags: BTreeMap::new(),
        }
    }
}

#[derive(Debug, Default)]
struct TableEnv {
    string_arrays: BTreeMap<String, Vec<String>>,
    tag_tables: BTreeMap<String, BTreeMap<String, f64>>,
    string_maps: BTreeMap<String, BTreeMap<String, String>>,
}

#[derive(Debug, Clone)]
pub struct CookingIngredients {
    pub values: BTreeMap<String, IngredientValue>,
    pub aliases: BTreeMap<String, String>,
}

/// Real prefabs that `scrapbook_prefabs.lua` deliberately comments out as
/// deprecated, but which are still generated by `prefabs/fish.lua` and are
/// valid crock-pot ingredients.
///
/// This list came out of the one-time `Data:DST Prefab` cross-validation
/// (`cooking_ingredient=true`): the local cooking.lua + scrapbook intersection
/// was exactly these two prefabs short of the wiki whitelist. Keep it short and
/// re-validate manually on game updates rather than turning wiki scraping into
/// a runtime dependency.
pub const EXTRA_REAL_PREFABS: &[&str] = &["fish", "fish_cooked"];

/// Parse `cooking.lua`: collect the ingredient table and the alias map.
pub fn parse_cooking_lua(source: &str) -> Result<CookingIngredients> {
    let ast = full_moon::parse(source).map_err(Error::LuaParse)?;
    let env = collect_table_env(&ast);
    let aliases = env.string_maps.get("aliases").cloned().unwrap_or_default();

    let mut values: BTreeMap<String, IngredientValue> = BTreeMap::new();
    for stmt in ast.nodes().stmts() {
        let ast::Stmt::FunctionCall(call) = stmt else {
            continue;
        };
        if call_head(call) != "AddIngredientValues" {
            continue;
        }
        let args = call_args(call).ok_or_else(|| {
            Error::ParseError(format!(
                "cooking.lua: cannot read arguments of `{}`",
                short_call(call)
            ))
        })?;
        if args.len() < 2 {
            return Err(Error::ParseError(format!(
                "cooking.lua: AddIngredientValues needs at least names and tags: `{}`",
                short_call(call)
            )));
        }

        let names = resolve_string_array(args[0], &env).ok_or_else(|| {
            Error::ParseError(format!(
                "cooking.lua: cannot resolve ingredient names in `{}`",
                short_call(call)
            ))
        })?;
        let tags = resolve_tags(args[1], &env).ok_or_else(|| {
            Error::ParseError(format!(
                "cooking.lua: cannot resolve ingredient tags in `{}`",
                short_call(call)
            ))
        })?;
        let cancook = args
            .get(2)
            .map(|e| eval_bool(e))
            .transpose()?
            .unwrap_or(false);
        let candry = args
            .get(3)
            .map(|e| eval_bool(e))
            .transpose()?
            .unwrap_or(false);

        for name in names {
            // Mirrors AddIngredientValues(): each call replaces the entry and
            // creates cooked/dried variants with the corresponding marker.
            values.insert(name.clone(), IngredientValue { tags: tags.clone() });
            if cancook {
                let mut cooked = IngredientValue::new();
                for (tag, value) in &tags {
                    cooked.tags.insert("precook".to_string(), 1.0);
                    cooked.tags.insert(tag.clone(), *value);
                }
                values.insert(format!("{}_cooked", name), cooked);
            }
            if candry {
                let mut dried = IngredientValue::new();
                for (tag, value) in &tags {
                    dried.tags.insert("dried".to_string(), 1.0);
                    dried.tags.insert(tag.clone(), *value);
                }
                values.insert(format!("{}_dried", name), dried);
            }
        }
    }

    if values.is_empty() {
        return Err(Error::ParseError(
            "cooking.lua produced no AddIngredientValues entries".to_string(),
        ));
    }
    Ok(CookingIngredients { values, aliases })
}

/// Parse `prefabs/oceanfishdef.lua` and return `<prefab>_inv` entries that
/// define `cooker_ingredient_value`.
pub fn parse_oceanfish(source: &str) -> Result<BTreeMap<String, IngredientValue>> {
    let ast = full_moon::parse(source).map_err(Error::LuaParse)?;
    let env = collect_table_env(&ast);
    let table = find_local_table(&ast, &["FISH_DEFS"]).ok_or_else(|| {
        Error::ParseError("prefabs/oceanfishdef.lua: FISH_DEFS table not found".to_string())
    })?;

    let mut out = BTreeMap::new();
    for field in table.fields() {
        let ast::Field::NameKey {
            value: ast::Expression::TableConstructor(def),
            ..
        } = field
        else {
            continue;
        };
        let Some(prefab) = nested_string(def, "prefab") else {
            continue;
        };
        let Some(value) = nested_value(def, "cooker_ingredient_value") else {
            continue;
        };
        if matches!(value, ast::Expression::Symbol(s) if s.token().to_string() == "nil") {
            continue;
        }
        let tags = resolve_tags(value, &env).ok_or_else(|| {
            Error::ParseError(format!(
                "prefabs/oceanfishdef.lua: cannot resolve cooker_ingredient_value for {}",
                prefab
            ))
        })?;
        out.insert(format!("{}_inv", prefab), IngredientValue { tags });
    }
    if out.is_empty() {
        return Err(Error::ParseError(
            "prefabs/oceanfishdef.lua: no cooking ingredient fish found".to_string(),
        ));
    }
    Ok(out)
}

/// Parse the real-prefab allow-list from `scrapbook_prefabs.lua`.
pub fn parse_scrapbook_prefabs(source: &str) -> Result<BTreeSet<String>> {
    let ast = full_moon::parse(source).map_err(Error::LuaParse)?;
    let table = find_local_table(&ast, &["PREFABS"]).ok_or_else(|| {
        Error::ParseError("scrapbook_prefabs.lua: PREFABS table not found".to_string())
    })?;
    let mut prefabs = BTreeSet::new();
    for field in table.fields() {
        if let ast::Field::ExpressionKey {
            key: ast::Expression::String(name),
            value: ast::Expression::Symbol(value),
            ..
        } = field
        {
            if value.token().to_string() == "true" {
                prefabs.insert(string_literal_text(&name.token().to_string()));
            }
        }
    }
    if prefabs.is_empty() {
        return Err(Error::ParseError(
            "scrapbook_prefabs.lua: no entries parsed".to_string(),
        ));
    }
    Ok(prefabs)
}

/// Convert the internal ingredient table into the selectable actual-prefab
/// list. `aliases` are `actual_prefab -> internal_key` (e.g.
/// `cookedsmallmeat -> smallmeat_cooked`).
pub fn selectable_ingredients(
    values: &BTreeMap<String, IngredientValue>,
    aliases: &BTreeMap<String, String>,
    actual_prefabs: &BTreeSet<String>,
) -> Vec<CookingIngredient> {
    let mut out: BTreeMap<String, CookingIngredient> = BTreeMap::new();

    for (key, value) in values {
        if actual_prefabs.contains(key) {
            out.insert(
                key.clone(),
                CookingIngredient {
                    prefab: key.clone(),
                    key: key.clone(),
                    tags: value.tags.clone(),
                    name_en: None,
                    name_zh: None,
                    icon: None,
                },
            );
        }
    }

    for (actual, key) in aliases {
        let Some(value) = values.get(key) else {
            continue;
        };
        if !actual_prefabs.contains(actual) {
            continue;
        }
        out.insert(
            actual.clone(),
            CookingIngredient {
                prefab: actual.clone(),
                key: key.clone(),
                tags: value.tags.clone(),
                name_en: None,
                name_zh: None,
                icon: None,
            },
        );
    }

    out.into_values().collect()
}

fn collect_table_env(ast: &Ast) -> TableEnv {
    let mut env = TableEnv::default();

    for stmt in ast.nodes().stmts() {
        match stmt {
            ast::Stmt::LocalAssignment(assignment) => {
                collect_assignment(
                    assignment.names().iter().map(|n| n.token().to_string()),
                    assignment.expressions().iter(),
                    &mut env,
                );
            }
            ast::Stmt::Assignment(assignment) => {
                let names = assignment.variables().iter().filter_map(|var| match var {
                    ast::Var::Name(name) => Some(name.token().to_string()),
                    _ => None,
                });
                collect_assignment(names, assignment.expressions().iter(), &mut env);
            }
            _ => {}
        }
    }
    env
}

fn collect_assignment<'a>(
    names: impl Iterator<Item = String>,
    expressions: impl Iterator<Item = &'a ast::Expression>,
    env: &mut TableEnv,
) {
    for (name, expr) in names.zip(expressions) {
        let ast::Expression::TableConstructor(table) = expr else {
            continue;
        };
        if let Some(array) = table_string_array(table) {
            env.string_arrays.insert(name.clone(), array);
        }
        if let Some(tags) = table_tags(table) {
            env.tag_tables.insert(name.clone(), tags);
        }
        if let Some(map) = table_string_map(table) {
            env.string_maps.insert(name, map);
        }
    }
}

fn table_string_array(table: &ast::TableConstructor) -> Option<Vec<String>> {
    let mut out = Vec::new();
    for field in table.fields() {
        match field {
            ast::Field::NoKey(ast::Expression::String(value)) => {
                out.push(string_literal_text(&value.token().to_string()));
            }
            _ => return None,
        }
    }
    if out.is_empty() {
        None
    } else {
        Some(out)
    }
}

fn table_tags(table: &ast::TableConstructor) -> Option<BTreeMap<String, f64>> {
    let mut out = BTreeMap::new();
    for field in table.fields() {
        if let ast::Field::NameKey { key, value, .. } = field {
            out.insert(key.token().to_string(), eval_number(value)?);
        } else {
            return None;
        }
    }
    if out.is_empty() {
        None
    } else {
        Some(out)
    }
}

fn table_string_map(table: &ast::TableConstructor) -> Option<BTreeMap<String, String>> {
    let mut out = BTreeMap::new();
    for field in table.fields() {
        match field {
            ast::Field::NameKey {
                key,
                value: ast::Expression::String(v),
                ..
            } => {
                out.insert(
                    key.token().to_string(),
                    string_literal_text(&v.token().to_string()),
                );
            }
            ast::Field::ExpressionKey {
                key: ast::Expression::String(k),
                value: ast::Expression::String(v),
                ..
            } => {
                out.insert(
                    string_literal_text(&k.token().to_string()),
                    string_literal_text(&v.token().to_string()),
                );
            }
            _ => return None,
        }
    }
    if out.is_empty() {
        None
    } else {
        Some(out)
    }
}

fn resolve_string_array(expr: &ast::Expression, env: &TableEnv) -> Option<Vec<String>> {
    match expr {
        ast::Expression::TableConstructor(table) => table_string_array(table),
        ast::Expression::Var(ast::Var::Name(name)) => {
            env.string_arrays.get(&name.token().to_string()).cloned()
        }
        ast::Expression::Parentheses { expression, .. } => resolve_string_array(expression, env),
        _ => None,
    }
}

fn resolve_tags(expr: &ast::Expression, env: &TableEnv) -> Option<BTreeMap<String, f64>> {
    match expr {
        ast::Expression::TableConstructor(table) => table_tags(table),
        ast::Expression::Var(ast::Var::Name(name)) => {
            env.tag_tables.get(&name.token().to_string()).cloned()
        }
        ast::Expression::Parentheses { expression, .. } => resolve_tags(expression, env),
        _ => None,
    }
}

fn eval_bool(expr: &ast::Expression) -> Result<bool> {
    match expr {
        ast::Expression::Symbol(symbol) => match symbol.token().to_string().as_str() {
            "true" => Ok(true),
            "false" => Ok(false),
            other => Err(Error::ParseError(format!(
                "cooking.lua: expected boolean, got `{}`",
                other
            ))),
        },
        other => Err(Error::ParseError(format!(
            "cooking.lua: expected boolean, got `{}`",
            other
        ))),
    }
}

fn eval_number(expr: &ast::Expression) -> Option<f64> {
    match expr {
        ast::Expression::Number(token) => token.token().to_string().trim().parse::<f64>().ok(),
        ast::Expression::Parentheses { expression, .. } => eval_number(expression),
        ast::Expression::UnaryOperator { unop, expression } => {
            let value = eval_number(expression)?;
            match unop {
                ast::UnOp::Minus(_) => Some(-value),
                _ => None,
            }
        }
        ast::Expression::BinaryOperator { lhs, binop, rhs } => {
            let left = eval_number(lhs)?;
            let right = eval_number(rhs)?;
            match binop {
                ast::BinOp::Plus(_) => Some(left + right),
                ast::BinOp::Minus(_) => Some(left - right),
                ast::BinOp::Star(_) => Some(left * right),
                ast::BinOp::Slash(_) => Some(left / right),
                _ => None,
            }
        }
        _ => None,
    }
}

fn find_local_table<'a>(ast: &'a Ast, names: &[&str]) -> Option<&'a ast::TableConstructor> {
    for stmt in ast.nodes().stmts() {
        let ast::Stmt::LocalAssignment(assignment) = stmt else {
            continue;
        };
        for (name, expr) in assignment
            .names()
            .iter()
            .zip(assignment.expressions().iter())
        {
            if !names.iter().any(|n| name.token().to_string() == *n) {
                continue;
            }
            if let ast::Expression::TableConstructor(table) = expr {
                return Some(table);
            }
        }
    }
    None
}

fn nested_value<'a>(table: &'a ast::TableConstructor, name: &str) -> Option<&'a ast::Expression> {
    table.fields().iter().find_map(|field| match field {
        ast::Field::NameKey { key, value, .. } if key.token().to_string() == name => Some(value),
        _ => None,
    })
}

fn nested_string(table: &ast::TableConstructor, name: &str) -> Option<String> {
    match nested_value(table, name)? {
        ast::Expression::String(value) => Some(string_literal_text(&value.token().to_string())),
        _ => None,
    }
}

fn call_head(call: &ast::FunctionCall) -> String {
    // `prefix().to_string()` includes leading trivia (comments/whitespace),
    // which can swallow a call whose previous line is a commented-out call.
    // Use the underlying token text instead.
    match call.prefix() {
        ast::Prefix::Name(name) => name.token().to_string(),
        _ => call.prefix().to_string().trim().to_string(),
    }
}

fn call_args(call: &ast::FunctionCall) -> Option<Vec<&ast::Expression>> {
    let suffix = call
        .suffixes()
        .filter_map(|suffix| match suffix {
            ast::Suffix::Call(call) => Some(call),
            _ => None,
        })
        .last()?;
    match suffix {
        ast::Call::AnonymousCall(ast::FunctionArgs::Parentheses { arguments, .. }) => {
            Some(arguments.iter().collect())
        }
        _ => None,
    }
}

fn short_call(call: &ast::FunctionCall) -> String {
    let text = call.to_string().replace('\n', " ");
    let text = text.split_whitespace().collect::<Vec<_>>().join(" ");
    if text.chars().count() > 120 {
        text.chars().take(117).collect::<String>() + "..."
    } else {
        text
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIXTURE: &str = r#"
local fruits = {"apple", "pear"}
local veggies = {"carrot"}
local aliases = { cookedapple = "apple_cooked" }

AddIngredientValues(fruits, {fruit=1}, true)
AddIngredientValues(veggies, {veggie=.5}, false, true)
AddIngredientValues({"honey"}, {sweetener=3}, true)
"#;

    #[test]
    fn parses_direct_calls_variants_and_aliases() {
        let parsed = parse_cooking_lua(FIXTURE).unwrap();
        assert_eq!(parsed.values["apple"].tags["fruit"], 1.0);
        assert_eq!(parsed.values["apple_cooked"].tags["precook"], 1.0);
        assert_eq!(parsed.values["apple_cooked"].tags["fruit"], 1.0);
        assert_eq!(parsed.values["carrot"].tags["veggie"], 0.5);
        assert_eq!(parsed.values["carrot_dried"].tags["dried"], 1.0);
        assert!(!parsed.values.contains_key("carrot_cooked"));
        assert_eq!(parsed.aliases["cookedapple"], "apple_cooked");
    }

    #[test]
    fn resolves_variable_tag_tables() {
        let source = r#"
COOKER_SMALL = { meat = .5, fish = .5 }
AddIngredientValues({"fish_inv"}, COOKER_SMALL, false)
"#;
        let parsed = parse_cooking_lua(source).unwrap();
        assert_eq!(parsed.values["fish_inv"].tags["meat"], 0.5);
    }

    #[test]
    fn filters_virtual_keys_with_allow_list() {
        let parsed = parse_cooking_lua(FIXTURE).unwrap();
        let actual: BTreeSet<String> = ["apple", "carrot"]
            .into_iter()
            .map(str::to_string)
            .collect();
        let selected = selectable_ingredients(&parsed.values, &parsed.aliases, &actual);
        let prefabs: Vec<&str> = selected.iter().map(|i| i.prefab.as_str()).collect();
        assert_eq!(prefabs, vec!["apple", "carrot"]);
        assert!(!prefabs.contains(&"apple_cooked"));
    }

    #[test]
    fn aliases_add_actual_prefab_when_internal_key_is_virtual() {
        let internal = BTreeMap::from([(
            "smallmeat_cooked".to_string(),
            IngredientValue {
                tags: BTreeMap::from([("meat".to_string(), 0.5)]),
            },
        )]);
        let aliases = BTreeMap::from([(
            "cookedsmallmeat".to_string(),
            "smallmeat_cooked".to_string(),
        )]);
        let actual = BTreeSet::from(["cookedsmallmeat".to_string()]);
        let selected = selectable_ingredients(&internal, &aliases, &actual);
        assert_eq!(selected.len(), 1);
        assert_eq!(selected[0].prefab, "cookedsmallmeat");
        assert_eq!(selected[0].key, "smallmeat_cooked");
    }

    #[test]
    fn parses_oceanfish_expansion_entries() {
        let source = r#"
COOKER_SMALL = { meat = .5, fish = .5 }
local FISH_DEFS =
{
    oceanfish_small_1 = {
        prefab = "oceanfish_small_1",
        cooker_ingredient_value = COOKER_SMALL,
    },
    oceanfish_small_2 = {
        prefab = "oceanfish_small_2",
        cooker_ingredient_value = { veggie = 1 },
    },
}
return { fish = FISH_DEFS }
"#;
        let fish = parse_oceanfish(source).unwrap();
        assert_eq!(fish["oceanfish_small_1_inv"].tags["fish"], 0.5);
        assert_eq!(fish["oceanfish_small_2_inv"].tags["veggie"], 1.0);
    }

    #[test]
    fn parses_scrapbook_allow_list() {
        let source = r#"
local PREFABS =
{
    ["apple"] = true,
    ["pear"] = true,
    --["ghost"] = true,
}
return PREFABS
"#;
        let prefabs = parse_scrapbook_prefabs(source).unwrap();
        assert!(prefabs.contains("apple"));
        assert!(prefabs.contains("pear"));
        assert!(!prefabs.contains("ghost"));
    }
}
